---
id: agilejapan-toyama
base_name: real-world-agile
tags: [agile]
presentation_date: 2016-06-25
version: 1.0.0
licenses: [MIT]
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Kunihiko Ito
  email: kuni.110.92@gmail.com
  rubygems_user: kunitoo
  slideshare_user: kunitoo
  speaker_deck_user: kunitoo
